### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/component-library#23]
To use these components in project repos, the plan is to require this as an npm dependency, yes?

If so, the package name will have to change and it will need to be published. Housing front-end is ready to put their site together. In the interim, we can use some `npm link` shenanigans, but we'll want to get this public soon.

**Comment by DavideDaniel** [comment]
That is the plan. We are happy to take on some contributions directly here as well. Immediate plan is to flesh out some  designs around common components, tracking component requests in our issues and surfacing close that can be shared across the platform. If the need is urgent, this can be pulled in via git in your package.json.

**Comment by DavideDaniel** [comment]
Closing this as we are published =)
