### ISSUE TITLE
Sankey diagram

### ISSUE THREAD

**Issue by palmerev** [hackoregon/component-library#34]
The budget team MVP includes an interactive Sankey diagram (or similar), for visualizing time series data:

> Featured Card:  Delta sankey diagram (or similar visualization) 
> Function: Represent the City of Portland’s budget data over a period of 10 years (data permitting), so users can quickly understand basic facts about the budget (service areas, general spending, changes over time) 
> Components:
> Visualization of budget data over time (e.g. a sankey diagram)
> Ability to manipulate a slider through the diagram, so they can land on each year. A pop-up box (or similar) will appear when users stop the slider on a particular year. The pop-up box will show budget data for that year, specifically total dollar amount and percent of total budget for each service area.
> Some contextualizing text about the diagram (to be written later)

**Comment by DavideDaniel** [comment]
How about leveraging https://github.com/nickbalestra/sankey ?

**Comment by palmerev** [comment]
Right. There will still be some work to do on the controls for the graph, etc. but this is a good start.

**Comment by DavideDaniel** [comment]
Are there related mocks for what's being asked for?

**Comment by DavideDaniel** [comment]
@palmerev -- thoughts on the sankey we put in recently.. does it fit the requirements for the basic component? The controls part should probably be part of a component that comprises both the sankey + the controls, or if the controls just affect the redux state & that's just reflected in a connected version of the sankey.

**Comment by DavideDaniel** [comment]
Sankey in component library but currently not being used..
