### ISSUE TITLE
Composed donut component with legend

### ISSUE THREAD

**Issue by tyreer** [hackoregon/component-library#35]
The _Leaflet map component tooltip_ (#33) will require a composed component with the existing Pie/Donut Visualization plus a legend.

We can look to the existing BarChart component for an example of a simple legend via Recharts. 
Recharts Legend General Component API: http://recharts.org/#/en-US/api/Legend

<img width="382" alt="screen shot 2017-03-16 at 11 02 40 am" src="https://cloud.githubusercontent.com/assets/20293876/24011853/2f7d88b2-0a39-11e7-8e11-53011d0b26a4.png">

**Comment by evandemaris** [comment]
Are we certain #33 will require this? I'd thought it would initially, but re-reading the spec, it sounds like the tooltip is intended to be general and allow each team to fill it with whatever they like.

**Comment by tyreer** [comment]
I'm not totally sure. Of course, David suggested it to class, so I'm more inclined than not to consider that it will be required. I know that housing will want a donut chart with a legend. 

The existing Pie component in the Storybook is made with D3, so I'm poking around to see what adding a legend option to the existing Pie component will entail. [d3-legend](https://github.com/susielu/d3-legend) seems like it could be an option. 

Alternately, Recharts has a [PieChart](http://recharts.org/#/en-US/api/PieChart) component that would be easy to add a Legend component to, which is what's being used in our Component Library BarChart component.

**Comment by tyreer** [comment]
[This documentation](http://d3-legend.susielu.com/) makes d3-legend look like a great approach, but I keep getting a “legendColor() is not a function” error when trying to implement it. Think I’ve got all the required dependencies in my feature branch, but certainly possible I’m setting it up incorrectly. Would love to hear if anyone else has more success with d3-legend.
