### ISSUE TITLE
Dot matrix chart

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/component-library#69]
Looking into how to visualize this - a dot matrix chart with custom icons

dot matrix visualization example (https://arpitnarechania.github.io/d3-dotmatrix/)

![sleeping provisions](https://cloud.githubusercontent.com/assets/2355543/24983510/47d9db86-1f9c-11e7-89b5-705a952c006d.png)

**Comment by DavideDaniel** [comment]
Are we able to get an svg of the people/dots?

**Comment by meganmckissack** [comment]
I'm going to check in with the team, I think that should be doable

**Comment by meganmckissack** [comment]
Closing this because they're going with a different and simpler visualization
